### ISSUE TITLE
error when running python-flask-server for agrold-api

### ISSUE THREAD

**Issue by pierrelarmande** [SouthGreenPlatform/AgroLD_webappV2#2]
When i run `python3 -m swagger_server`
I got the following error:
Traceback (most recent call last):
  File "/Users/plarmande/anaconda3/envs/agrold/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/plarmande/anaconda3/envs/agrold/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/plarmande/PycharmProjects/AgroLD_webappV2/python-flask-server/swagger_server/__main__.py", line 3, in <module>
    from forms.searchForms import SearchForm
ModuleNotFoundError: No module named 'forms'

**Comment by pierrelarmande** [comment]
solved installing module connexion==2.6.0
